"use strict";var road_black;var road_path;var scooter_elem;var scroll_position;var last_scroll_position=0;var road_top;var road_start;var road_end;var road_points=[];var lerps=[0,0,0,0,0,0,0,0];var sharing;window.addEventListener("load",road_animate_init,false);(function(){var lastTime=0;var vendors=['webkit','moz'];for(var x=0;x<vendors.length&&!window.requestAnimationFrame;++x){window.requestAnimationFrame=window[vendors[x]+'RequestAnimationFrame'];window.cancelAnimationFrame=window[vendors[x]+'CancelAnimationFrame']||window[vendors[x]+'CancelRequestAnimationFrame'];}
if(!window.requestAnimationFrame)
window.requestAnimationFrame=function(callback,element){var currTime=new Date().getTime();var timeToCall=Math.max(0,16-(currTime-lastTime));var id=window.setTimeout(function(){callback(currTime+timeToCall);},timeToCall);lastTime=currTime+timeToCall;return id;};if(!window.cancelAnimationFrame)
window.cancelAnimationFrame=function(id){clearTimeout(id);};}());var InfoIcon=function(){this.icon;this.text;}
function road_animate_init(){road_black=document.querySelector('.blue-road');road_path=document.getElementById('road-path-target');scooter_elem=document.querySelector('.scroll-car');var road_elements=document.querySelectorAll('.content-box');var n=road_elements.length;for(var i=0;i<n;++i){var element=road_elements[i];var icon=new InfoIcon();icon.icon=element.querySelector('.info-icon');icon.text=element.querySelector('.info-text');icon.icon.style.opacity=0;icon.icon.style.transform="scale(0,0)";icon.text.style.opacity=0;road_points.push(icon);}
window.addEventListener('scroll',on_scroll,false);road_start=road_path.getPointAtLength(0);road_end=road_start+road_path.getTotalLength()+100;var win_width=window.innerWidth||document.documentElement.clientWidth||document.body.clientWidth;requestAnimationFrame(road_upA);}
function on_scroll(e){if(typeof window.scrollY!=='undefined'){scroll_position=window.scrollY;}else{scroll_position=document.documentElement.scrollTop;}}
function road_upA(t){road_update();requestAnimationFrame(road_upB);}
function road_upB(t){road_update();requestAnimationFrame(road_upA);}
function road_update(){if(scroll_position>300)
{var t=0.5;var scroll=(1-t)*last_scroll_position+t*scroll_position;last_scroll_position=scroll_position;if(scroll<0)scroll=0;if(scroll>road_end)
scroll=road_end;var start=road_start;var pa=road_path.getPointAtLength(scroll);var pb=road_path.getPointAtLength(scroll+10);var vx=pb.x-pa.x;var vy=pb.y-pa.y;var angle=(Math.atan2(vy,vx)*57.2957795);var dx=(pb.x-start.x)+64;var dy=(pb.y-start.y);update_transform(scooter_elem,1,1,dx,dy,-angle-180);var start=30;var end=1000;for(var i=0;i<8;++i)
{var t=clamp((scroll-start)/(end-start),0,1);start+=500;end+=500;road_points[i].icon.style.opacity=t;road_points[i].icon.style.transform="scale("+t+","+t+")";road_points[i].text.style.opacity=cubic_bezier(0,0,0,1,t);}}}
function clamp(val,min,max){if(val<min)return min;else if(val>max)return max;return val;}
function cubic_bezier(a,b,c,d,t){var cy=3*(b-a);var by=3*(c-b)-cy;var ay=d-a-cy-by;var tt=t*t;var ttt=tt*t;var r=(ay*ttt)+(by*tt)+(cy*t)+a;return r;}
function update_transform(ent,sx,sy,tx,ty,r){var ang=r*Consts.DEG2RAD;var a=Math.cos(ang);var b=-Math.sin(ang);var c=tx;var d=Math.sin(ang);var e=Math.cos(ang);var f=ty;var matrix="matrix("+a+","+b+","+d+","+e+","+c+","+f+")";ent.style["webkitTransform"]=matrix;ent.style.MozTransform=matrix;ent.style["oTransform"]=matrix;ent.style["msTransform"]=matrix;ent.style["transform"]=matrix;}